include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: debian:unstable

before_script:
  - apt update -qq
  - apt install -y -qq build-essential autoconf automake help2man
                       autoconf-archive texinfo texlive git
  - git clone https://github.com/ashinn/chibi-scheme.git --depth 1
  - cd chibi-scheme
  - make
  - make install
  - cd ..

stages:
  - build

build-distcheck:
  stage: build
  script:
    - ./bootstrap
    - mkdir build
    - cd build
    - ../configure
    - make V=1 -j2 distcheck
    - cp -p `echo '@PACKAGE_TARNAME@-@PACKAGE_VERSION@.tar.gz'
             | ./config.status --file=-` unsyntax-latest.tar.gz
    - make pdf
  artifacts:
    when: always
    paths:
      - build/*
    expire_in: 1 week
